import ReactMarkdown from "react-markdown"

const markdownComponents = {
    h1: ({ children }) => <h1 style={{ color: "#e2e8f0", fontSize: "1rem", fontWeight: "700", marginBottom: "8px", marginTop: "16px" }}>{children}</h1>,
    h2: ({ children }) => <h2 style={{ color: "#e2e8f0", fontSize: "0.9rem", fontWeight: "700", marginBottom: "6px", marginTop: "14px" }}>{children}</h2>,
    h3: ({ children }) => <h3 style={{ color: "#cbd5e1", fontSize: "0.82rem", fontWeight: "600", marginBottom: "4px", marginTop: "12px" }}>{children}</h3>,
    h4: ({ children }) => <h4 style={{ color: "#cbd5e1", fontSize: "0.78rem", fontWeight: "600", marginBottom: "4px", marginTop: "10px" }}>{children}</h4>,
    p: ({ children }) => <p style={{ color: "#8899aa", fontSize: "0.8rem", lineHeight: "1.8", marginBottom: "8px" }}>{children}</p>,
    li: ({ children }) => <li style={{ color: "#8899aa", fontSize: "0.78rem", lineHeight: "1.7", marginBottom: "4px" }}>{children}</li>,
    ul: ({ children }) => <ul style={{ paddingLeft: "20px", marginBottom: "8px" }}>{children}</ul>,
    ol: ({ children }) => <ol style={{ paddingLeft: "20px", marginBottom: "8px" }}>{children}</ol>,
    strong: ({ children }) => {
        const text = String(children)
        const color = text.includes("CRITICAL") ? "#f87171" : text.includes("HIGH") ? "#fb923c" : text.includes("MEDIUM") ? "#fbbf24" : text.includes("LOW") ? "#4ade80" : "#e2e8f0"
        return <strong style={{ color, fontWeight: "700" }}>{children}</strong>
    },
    hr: () => <hr style={{ border: "none", borderTop: "1px solid #1c1c22", margin: "16px 0" }} />,
    code: ({ children }) => <code style={{ background: "#1c1c22", color: "#fb923c", padding: "2px 6px", borderRadius: "4px", fontSize: "0.75rem" }}>{children}</code>,
    pre: ({ children }) => <pre style={{ background: "#0d0d0f", border: "1px solid #1c1c22", borderRadius: "6px", padding: "12px", overflowX: "auto", fontSize: "0.75rem", marginBottom: "8px" }}>{children}</pre>,
    a: ({ children, href }) => <a href={href} target="_blank" rel="noreferrer" style={{ color: "#60a5fa", textDecoration: "underline" }}>{children}</a>,
}

export default function Report({ result }) {
    if (result.error) return (
        <div style={{ color: "#f87171", padding: "20px", background: "#1a0a0a", border: "1px solid #7f1d1d", borderRadius: "10px" }}>
            {result.error}
        </div>
    )

    const critCount = (result.report.match(/CRITICAL/g) || []).length
    const highCount = (result.report.match(/\bHIGH\b/g) || []).length
    const medCount = (result.report.match(/MEDIUM/g) || []).length
    const lowCount = (result.report.match(/\bLOW\b/g) || []).length

    return (
        <div style={{ display: "flex", flexDirection: "column", gap: "16px", minWidth: 0 }}>
            {/* Stat cards */}
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: "12px" }}>
                {[
                    { label: "Files Scanned", value: result.files_scanned, color: "#e2e8f0", sub: "across repo" },
                    { label: "Critical", value: critCount, color: "#f87171", sub: "findings" },
                    { label: "High", value: highCount, color: "#fb923c", sub: "findings" },
                    { label: "Medium / Low", value: `${medCount} / ${lowCount}`, color: "#fbbf24", sub: "findings" },
                ].map(s => (
                    <div key={s.label} style={{ padding: "20px", background: "#141418", border: "1px solid #1c1c22", borderRadius: "10px", minWidth: 0 }}>
                        <div style={{ fontSize: "0.7rem", color: "#555", marginBottom: "10px", fontWeight: "500" }}>{s.label.toUpperCase()}</div>
                        <div style={{ fontSize: "1.6rem", fontWeight: "700", color: s.color, marginBottom: "4px" }}>{s.value}</div>
                        <div style={{ fontSize: "0.7rem", color: "#444" }}>{s.sub}</div>
                    </div>
                ))}
            </div>

            {/* Report body */}
            <div style={{ background: "#141418", border: "1px solid #1c1c22", borderRadius: "10px", overflow: "hidden", minWidth: 0 }}>
                <div style={{ padding: "14px 20px", borderBottom: "1px solid #1c1c22", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <span style={{ fontSize: "0.8rem", fontWeight: "600" }}>Security Report</span>
                    <span style={{ fontSize: "0.68rem", color: "#555" }}>Generated by 5-agent swarm</span>
                </div>
                <div style={{ padding: "20px", maxHeight: "520px", overflowY: "auto" }}>
                    <ReactMarkdown components={markdownComponents}>
                        {result.report}
                    </ReactMarkdown>
                </div>
            </div>

            {/* Agent telemetry */}
            <div style={{ fontSize: "0.75rem", color: "#555", fontWeight: "500" }}>RAW AGENT OUTPUT</div>
            {["planner", "secrets", "dependency", "logic"].map(agent => (
                <details key={agent} style={{ background: "#141418", border: "1px solid #1c1c22", borderRadius: "10px", overflow: "hidden" }}>
                    <summary style={{ padding: "14px 20px", cursor: "pointer", fontSize: "0.78rem", color: "#666", fontWeight: "500", listStyle: "none", display: "flex", justifyContent: "space-between" }}>
                        <span>{agent.charAt(0).toUpperCase() + agent.slice(1)} Agent</span>
                        <span style={{ color: "#444" }}>▸ Expand</span>
                    </summary>
                    <div style={{ padding: "16px 20px", borderTop: "1px solid #1c1c22", maxHeight: "400px", overflowY: "auto" }}>
                        <ReactMarkdown components={markdownComponents}>
                            {result.agents[agent]}
                        </ReactMarkdown>
                    </div>
                </details>
            ))}
        </div>
    )
}